/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DevUiRouteImport } from './routes/dev.ui'
import { Route as WorkflowsIdRouteImport } from './routes/workflows.$id'
import { Route as WorkflowsIdIndexRouteImport } from './routes/workflows.$id.index'
import { Route as WorkflowsIdDefinitionRouteImport } from './routes/workflows.$id.definition'
import { Route as WorkflowsIdRunsRouteImport } from './routes/workflows.$id.runs'
import { Route as WorkflowsIdRunsRunIdRouteImport } from './routes/workflows.$id.runs.$runId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DevUiRoute = DevUiRouteImport.update({
  id: '/dev/ui',
  path: '/dev/ui',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdRoute = WorkflowsIdRouteImport.update({
  id: '/workflows/$id',
  path: '/workflows/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkflowsIdIndexRoute = WorkflowsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkflowsIdRoute,
} as any)
const WorkflowsIdDefinitionRoute = WorkflowsIdDefinitionRouteImport.update({
  id: '/definition',
  path: '/definition',
  getParentRoute: () => WorkflowsIdRoute,
} as any)
const WorkflowsIdRunsRoute = WorkflowsIdRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => WorkflowsIdRoute,
} as any)
const WorkflowsIdRunsRunIdRoute = WorkflowsIdRunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => WorkflowsIdRunsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dev/ui': typeof DevUiRoute
  '/workflows/$id': typeof WorkflowsIdRouteWithChildren
  '/workflows/$id/definition': typeof WorkflowsIdDefinitionRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRouteWithChildren
  '/workflows/$id/': typeof WorkflowsIdIndexRoute
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dev/ui': typeof DevUiRoute
  '/workflows/$id/definition': typeof WorkflowsIdDefinitionRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRouteWithChildren
  '/workflows/$id': typeof WorkflowsIdIndexRoute
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dev/ui': typeof DevUiRoute
  '/workflows/$id': typeof WorkflowsIdRouteWithChildren
  '/workflows/$id/definition': typeof WorkflowsIdDefinitionRoute
  '/workflows/$id/runs': typeof WorkflowsIdRunsRouteWithChildren
  '/workflows/$id/': typeof WorkflowsIdIndexRoute
  '/workflows/$id/runs/$runId': typeof WorkflowsIdRunsRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dev/ui'
    | '/workflows/$id'
    | '/workflows/$id/definition'
    | '/workflows/$id/runs'
    | '/workflows/$id/'
    | '/workflows/$id/runs/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dev/ui'
    | '/workflows/$id/definition'
    | '/workflows/$id/runs'
    | '/workflows/$id'
    | '/workflows/$id/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/dev/ui'
    | '/workflows/$id'
    | '/workflows/$id/definition'
    | '/workflows/$id/runs'
    | '/workflows/$id/'
    | '/workflows/$id/runs/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DevUiRoute: typeof DevUiRoute
  WorkflowsIdRoute: typeof WorkflowsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/ui': {
      id: '/dev/ui'
      path: '/dev/ui'
      fullPath: '/dev/ui'
      preLoaderRoute: typeof DevUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id': {
      id: '/workflows/$id'
      path: '/workflows/$id'
      fullPath: '/workflows/$id'
      preLoaderRoute: typeof WorkflowsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workflows/$id/': {
      id: '/workflows/$id/'
      path: '/'
      fullPath: '/workflows/$id/'
      preLoaderRoute: typeof WorkflowsIdIndexRouteImport
      parentRoute: typeof WorkflowsIdRoute
    }
    '/workflows/$id/definition': {
      id: '/workflows/$id/definition'
      path: '/definition'
      fullPath: '/workflows/$id/definition'
      preLoaderRoute: typeof WorkflowsIdDefinitionRouteImport
      parentRoute: typeof WorkflowsIdRoute
    }
    '/workflows/$id/runs': {
      id: '/workflows/$id/runs'
      path: '/runs'
      fullPath: '/workflows/$id/runs'
      preLoaderRoute: typeof WorkflowsIdRunsRouteImport
      parentRoute: typeof WorkflowsIdRoute
    }
    '/workflows/$id/runs/$runId': {
      id: '/workflows/$id/runs/$runId'
      path: '/$runId'
      fullPath: '/workflows/$id/runs/$runId'
      preLoaderRoute: typeof WorkflowsIdRunsRunIdRouteImport
      parentRoute: typeof WorkflowsIdRunsRoute
    }
  }
}

interface WorkflowsIdRunsRouteChildren {
  WorkflowsIdRunsRunIdRoute: typeof WorkflowsIdRunsRunIdRoute
}

const WorkflowsIdRunsRouteChildren: WorkflowsIdRunsRouteChildren = {
  WorkflowsIdRunsRunIdRoute: WorkflowsIdRunsRunIdRoute,
}

const WorkflowsIdRunsRouteWithChildren = WorkflowsIdRunsRoute._addFileChildren(
  WorkflowsIdRunsRouteChildren,
)

interface WorkflowsIdRouteChildren {
  WorkflowsIdDefinitionRoute: typeof WorkflowsIdDefinitionRoute
  WorkflowsIdRunsRoute: typeof WorkflowsIdRunsRouteWithChildren
  WorkflowsIdIndexRoute: typeof WorkflowsIdIndexRoute
}

const WorkflowsIdRouteChildren: WorkflowsIdRouteChildren = {
  WorkflowsIdDefinitionRoute: WorkflowsIdDefinitionRoute,
  WorkflowsIdRunsRoute: WorkflowsIdRunsRouteWithChildren,
  WorkflowsIdIndexRoute: WorkflowsIdIndexRoute,
}

const WorkflowsIdRouteWithChildren = WorkflowsIdRoute._addFileChildren(
  WorkflowsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DevUiRoute: DevUiRoute,
  WorkflowsIdRoute: WorkflowsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
